### ISSUE TITLE
ban* doesn't handle updating new bans (existing bans should be added!)

### ISSUE THREAD

**Issue by abma** [spring/uberserver#112]
2014-10-25T14:24:51 Traceback (most recent call last):
2014-10-25T14:24:51   File "/home/lobby/uberserver/Dispatcher.py", line 39, in callback
2014-10-25T14:24:51     self.socketmap[s].Handle(data)
2014-10-25T14:24:51   File "/home/lobby/uberserver/Client.py", line 144, in Handle
2014-10-25T14:24:51     self._protocol._handle(self,cmd)
2014-10-25T14:24:51   File "/home/lobby/uberserver/protocol/Protocol.py", line 302, in _handle
2014-10-25T14:24:51     function(client)
2014-10-25T14:24:51   File "/home/lobby/uberserver/protocol/Protocol.py", line 2682, in in_BAN
2014-10-25T14:24:51     @required.str username: The target user.
2014-10-25T14:24:51   File "/home/lobby/uberserver/SQLUsers.py", line 344, in ban_user
2014-10-25T14:24:51     session.commit()
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/session.py", line 721, in commit
2014-10-25T14:24:51     self.transaction.commit()
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/session.py", line 354, in commit
2014-10-25T14:24:51     self._prepare_impl()
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/session.py", line 334, in _prepare_impl
2014-10-25T14:24:51     self.session.flush()
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/session.py", line 1818, in flush
2014-10-25T14:24:51     self._flush(objects)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/session.py", line 1936, in _flush
2014-10-25T14:24:51     transaction.rollback(_capture_exception=True)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/util/langhelpers.py", line 58, in __exit__
2014-10-25T14:24:51     compat.reraise(exc_type, exc_value, exc_tb)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/session.py", line 1900, in _flush
2014-10-25T14:24:51     flush_context.execute()
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/unitofwork.py", line 372, in execute
2014-10-25T14:24:51     rec.execute(self)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/unitofwork.py", line 525, in execute
2014-10-25T14:24:51     uow
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/persistence.py", line 64, in save_obj
2014-10-25T14:24:51     table, insert)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/orm/persistence.py", line 569, in _emit_insert_statements
2014-10-25T14:24:51     execute(statement, params)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/engine/base.py", line 662, in execute
2014-10-25T14:24:51     params)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
2014-10-25T14:24:51     compiled_sql, distilled_params
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/engine/base.py", line 874, in _execute_context
2014-10-25T14:24:51     context)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
2014-10-25T14:24:51     exc_info
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/util/compat.py", line 195, in raise_from_cause
2014-10-25T14:24:51     reraise(type(exception), exception, tb=exc_tb)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/engine/base.py", line 867, in _execute_context
2014-10-25T14:24:51     context)
2014-10-25T14:24:51   File "/home/lobby/uberserver/sqlalchemy/engine/default.py", line 324, in do_execute
2014-10-25T14:24:51     cursor.execute(statement, parameters)
2014-10-25T14:24:51   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
2014-10-25T14:24:51     self.errorhandler(self, exc, value)
2014-10-25T14:24:51   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
2014-10-25T14:24:51     raise errorclass, errorvalue
2014-10-25T14:24:51 IntegrityError: (IntegrityError) "Duplicate entry ..."
2014-10-25T14:24:51 
2014-10-25T14:24:51 ------------------------------------------------------------

**Comment by abma** [comment]
duplicates are allowed now
