### ISSUE TITLE
traceback error in in_JOIN (encoding issue loaded from db)

### ISSUE THREAD

**Issue by abma** [spring/uberserver#156]
2015-03-08T01:30:34 Traceback (most recent call last):
2015-03-08T01:30:34   File "/home/lobby/uberserver/Dispatcher.py", line 41, in callback
2015-03-08T01:30:34     self.socketmap[s].Handle(data)
2015-03-08T01:30:34   File "/home/lobby/uberserver/Client.py", line 207, in Handle
2015-03-08T01:30:34     self.HandleProtocolCommands(self.data.split(DATA_PARTIT_BYTE), msg_limits)
2015-03-08T01:30:34   File "/home/lobby/uberserver/Client.py", line 290, in HandleProtocolCommands
2015-03-08T01:30:34     self.HandleProtocolCommand(command)
2015-03-08T01:30:34   File "/home/lobby/uberserver/Client.py", line 297, in HandleProtocolCommand
2015-03-08T01:30:34     self._protocol._handle(self, cmd)
2015-03-08T01:30:34   File "/home/lobby/uberserver/protocol/Protocol.py", line 352, in _handle
2015-03-08T01:30:34     function(*([client] + fun_args))
2015-03-08T01:30:34   File "/home/lobby/uberserver/protocol/Protocol.py", line 1571, in in_JOIN
2015-03-08T01:30:34     client.Send("SAID %s %s %s" %(chan, msg[1], msg[2]))
2015-03-08T01:30:34 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 23: ordinal not in range(128)

**Comment by abma** [comment]
related to #154

**Comment by abma** [comment]
needs lobby server restart

**Comment by abma** [comment]
restarted a few minutes ago. error seems gone! :)

(just springlobby hanged for 50 seconds because it received messages of a ~month :D)
