### ISSUE TITLE
inconsistency in users inside battles

### ISSUE THREAD

**Issue by abma** [spring/uberserver#166]
https://github.com/springlobby/springlobby/issues/425

seems users are offline but still in battle.

CLEANUP returned sth. != 0

**Comment by abma** [comment]
2015-05-08T19:09:51 Traceback (most recent call last):
2015-05-08T19:09:51   File "/home/lobby/uberserver/Dispatcher.py", line 37, in callback
2015-05-08T19:09:51     self.socketmap[s].Handle(data)
2015-05-08T19:09:51   File "/home/lobby/uberserver/Client.py", line 207, in Handle
2015-05-08T19:09:51     self.HandleProtocolCommands(self.data.split(DATA_PARTIT_BYTE), msg_limits)
2015-05-08T19:09:51   File "/home/lobby/uberserver/Client.py", line 290, in HandleProtocolCommands
2015-05-08T19:09:51     self.HandleProtocolCommand(command)
2015-05-08T19:09:51   File "/home/lobby/uberserver/Client.py", line 297, in HandleProtocolCommand
2015-05-08T19:09:51     self._protocol._handle(self, cmd)
2015-05-08T19:09:51   File "/home/lobby/uberserver/protocol/Protocol.py", line 351, in _handle
2015-05-08T19:09:51     function(*([client] + fun_args))
2015-05-08T19:09:51   File "/home/lobby/uberserver/protocol/Protocol.py", line 1124, in in_SAY
2015-05-08T19:09:51     msg = self.SayHooks.hook_SAY(self, client, channel, msg)
2015-05-08T19:09:51   File "/home/lobby/uberserver/SayHooks.py", line 132, in hook_SAY
2015-05-08T19:09:51     channel.muteUser(self._root.chanserv, client, 15, ip=True, quiet=True)
2015-05-08T19:09:51 TypeError: muteUser() got an unexpected keyword argument 'ip'
