### ISSUE TITLE
Traceback Protocol.py", line 1965, in 

### ISSUE THREAD

**Issue by abma** [spring/uberserver#167]
2015-05-08T20:09:03 Traceback (most recent call last):
2015-05-08T20:09:03   File "/home/lobby/uberserver/Dispatcher.py", line 37, in callback
2015-05-08T20:09:03     self.socketmap[s].Handle(data)
2015-05-08T20:09:03   File "/home/lobby/uberserver/Client.py", line 207, in Handle
2015-05-08T20:09:03     self.HandleProtocolCommands(self.data.split(DATA_PARTIT_BYTE), msg_limits)
2015-05-08T20:09:03   File "/home/lobby/uberserver/Client.py", line 290, in HandleProtocolCommands
2015-05-08T20:09:03     self.HandleProtocolCommand(command)
2015-05-08T20:09:03   File "/home/lobby/uberserver/Client.py", line 297, in HandleProtocolCommand
2015-05-08T20:09:03     self._protocol._handle(self, cmd)
2015-05-08T20:09:03   File "/home/lobby/uberserver/protocol/Protocol.py", line 351, in _handle
2015-05-08T20:09:03     function(*([client] + fun_args))
2015-05-08T20:09:03   File "/home/lobby/uberserver/protocol/Protocol.py", line 1862, in in_JOINBATTLEACCEPT
2015-05-08T20:09:03     self.in_JOINBATTLE(user, battle_id)
2015-05-08T20:09:03   File "/home/lobby/uberserver/protocol/Protocol.py", line 1965, in in_JOINBATTLE
2015-05-08T20:09:03     battle_user = self._root.usernames[user]
2015-05-08T20:09:03 KeyError: u'1Poni'

**Comment by abma** [comment]
atm i assume its fixed via https://github.com/spring/uberserver/commit/2b0bf46fa54d16d32afcd6b1ddd74514f75e1dc0
