### ISSUE TITLE
python3 server.pem creation problem

### ISSUE THREAD

**Issue by geedubess** [spring/uberserver#198]
@ current git head ac1999b2a72b1fc42f02d657bd1ca1e70ed0e669
Super-lazy-style defect report.

```
Generating self-signed certificate server.pem
Traceback (most recent call last):
  File "./server.py", line 57, in <module>
    _root.init()
  File "/x/uberserver/DataHandler.py", line 121, in init
    self.parseFiles()
  File "/x/uberserver/DataHandler.py", line 287, in parseFiles
    self.loadCertificates()
  File "/x/uberserver/DataHandler.py", line 252, in loadCertificates
    certificate.create_self_signed_cert(certfile)
  File "/x/uberserver/certificate.py", line 30, in create_self_signed_cert
    cert.set_notBefore(when)
  File "/x/.local/lib/python3.5/site-packages/OpenSSL/crypto.py", line 1256, in set_notBefore
    return self._set_boundary_time(_lib.X509_get_notBefore, when)
  File "/x/.local/lib/python3.5/site-packages/OpenSSL/crypto.py", line 1241, in _set_boundary_time
    return _set_asn1_time(which(self._x509), when)
  File "/x/.local/lib/python3.5/site-packages/OpenSSL/crypto.py", line 106, in _set_asn1_time
    raise TypeError("when must be a byte string")
TypeError: when must be a byte string


--- a/certificate.py
+++ b/certificate.py
@@ -5,7 +5,7 @@ from OpenSSL import crypto
 import time

 def timestr():
-       return time.strftime("%Y%m%d%H%M%SZ", time.gmtime())
+       return time.strftime("%Y%m%d%H%M%SZ", time.gmtime()).encode('utf-8')

 def create_self_signed_cert(filename):
        # creates a serlf-signed certificate
@@ -35,8 +35,8 @@ def create_self_signed_cert(filename):
        cert.sign(k, 'sha1')

        f = open(filename, "wt")
-       f.write(crypto.dump_certificate(crypto.FILETYPE_PEM, cert))
-       f.write(crypto.dump_privatekey(crypto.FILETYPE_PEM, k))
+       f.write(crypto.dump_certificate(crypto.FILETYPE_PEM, cert).decode('ascii'))
+       f.write(crypto.dump_privatekey(crypto.FILETYPE_PEM, k).decode('ascii'))
        f.close()

```

**Comment by TurBoss** [comment]
hit this too
