### ISSUE TITLE
NameError: name 'battle_id' is not defined

### ISSUE THREAD

**Issue by abma** [spring/uberserver#210]
2017-05-02 01:28:33 ERROR DataHandler.error:330  Error in handling data from client: [ACE]Perge name 'battle_id' is not defined, b'JOINBATTLEACCEPT Ruggi\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 37, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 160, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), msg_limits)
  File "/home/lobby/uberserver/Client.py", line 210, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 166, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 298, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1720, in in_JOINBATTLEACCEPT
    self._joinBattle(user, battle)
  File "protocol/Protocol.py", line 1691, in _joinBattle
    client.Send('ADDBOT %s %s' % (battle_id, iter)+' %(owner)s %(battlestatus)s %(teamcolor)s %(AIDLL)s' % (bot))
NameError: name 'battle_id' is not defined

**Comment by abma** [comment]
c44b9b62
