### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'session_id'

### ISSUE THREAD

**Issue by abma** [spring/uberserver#211]
2017-05-02 01:28:46 ERROR DataHandler.error:330  Error in handling data from client: MC2 'NoneType' object has no attribute 'session_id', b'#1 LOGIN ...\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 37, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 160, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), msg_limits)
  File "/home/lobby/uberserver/Client.py", line 210, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 166, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 298, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 897, in in_LOGIN
    self._SendLoginInfo(client)
  File "protocol/Protocol.py", line 924, in _SendLoginInfo
    if not battleclient.session_id == battle.host:
AttributeError: 'NoneType' object has no attribute 'session_id'

**Comment by abma** [comment]
can't reproduce. very likely just a side-effect of inconsitency / bugs in JOINBATTLE
