### ISSUE TITLE
KeyError: None

### ISSUE THREAD

**Issue by abma** [spring/uberserver#212]
2017-05-02 01:28:47 ERROR DataHandler.error:330  Error in handling data from client: Ruggi None, b'#22 SAYBATTLE !ring\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 37, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 160, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), msg_limits)
  File "/home/lobby/uberserver/Client.py", line 210, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 166, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 298, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1562, in in_SAYBATTLE
    battle = self._root.battles[battle_id]
KeyError: None

**Comment by abma** [comment]
can't reproduce. very likely just a side-effect of inconsitency / bugs in JOINBATTLE
