### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ignored'

### ISSUE THREAD

**Issue by abma** [spring/uberserver#213]
2017-05-02 01:33:02 ERROR DataHandler.error:330  Error in handling data from client: [ACE]Synchronous 'NoneType' object has no attribute 'ignored', b'SAYBATTLEEX * WELCOME Hakora (Rank 10 - Newbie) on [ACE]Servers (SPADS 0.11.43a).\nSAYBATTLEPRIVATEEX Hakora * Chicken help on http://ace.springrts.fr/tips-tricks-chicken-games ~ Need some general help ? Type \xc2\xab!h\xc2\xbb.\nSAYBATTLEPRIVATEEX Hakora * Tip : \xc2\xab!lock\xc2\xbb / \xc2\xab!unlock\xc2\xbb for private games.\nSAYBATTLEPRIVATEEX Hakora * [ACE]Autohosts website at http://ace.springrts.fr ~ SpringRTS en fran\xc3\xa7ais ici http://springrts.fr\nSAYBATTLEPRIVATEEX Hakora * You can contact [ACE]Associates at http://ace.springrts.fr/contact-aceassociates for any requests~suggests.\nSETSCRIPTTAGS game/players/hakora/skill=#30#\nSAYBATTLEEX * WELCOME Hakora (Rank 10 - Newbie) on [ACE]Servers (SPADS 0.11.43a).\nSAYBATTLEPRIVATEEX Hakora * Chicken help on http://ace.springrts.fr/tips-tricks-chicken-games ~ Need some general help ? Type \xc2\xab!h\xc2\xbb.\nSAYBATTLEPRIVATEEX Hakora * Tip : \xc2\xab!lock\xc2\xbb / \xc2\xab!unlock\xc2\xbb for private games.\nSAYBATTLEPRIVATEEX Hakora * [ACE]Autohosts website at http://ace.springrts.fr ~ SpringRTS en fran\xc3\xa7ais ici http://springrts.fr\nSAYBATTLEPRIVATEEX Hakora * You can contact [ACE]Associates at http://ace.springrts.fr/contact-aceassociates for any requests~suggests.\nSETSCRIPTTAGS game/players/hakora/skill=#30#\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 37, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 160, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), msg_limits)
  File "/home/lobby/uberserver/Client.py", line 210, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 166, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 298, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1574, in in_SAYBATTLEEX
    self.broadcast_SendBattle(battle, 'SAIDBATTLEEX %s %s' % (client.username, msg), client)
  File "protocol/Protocol.py", line 617, in broadcast_SendBattle
    if sourceClient == None or not sourceClient.db_id in client.ignored:
AttributeError: 'NoneType' object has no attribute 'ignored'

**Comment by abma** [comment]
can't reproduce. very likely just a side-effect of inconsitency / bugs in JOINBATTLE
