### ISSUE TITLE
CHANGEPASSWORD broken

### ISSUE THREAD

**Issue by abma** [spring/uberserver#226]
017-09-21 17:26:43 ERROR twistedserver.dataReceived:53  Error in handling data from client: ... 'Chat' object has no attribute 'use_secure_session', b'CHANGEPASSWORD ...\r\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 51, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 159, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), msg_limits)
  File "/home/lobby/uberserver/Client.py", line 209, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 165, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 302, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 2544, in in_CHANGEPASSWORD
    if (client.use_secure_session()):
AttributeError: 'Chat' object has no attribute 'use_secure_session'

**Comment by abma** [comment]
hopefully fixed by https://github.com/spring/uberserver/commit/9cfe7e2117c0df8848973d61771feb7d77170c08
