### ISSUE TITLE
uberserver can't automaticly reconnect when database server restarts / goes away

### ISSUE THREAD

**Issue by abma** [spring/uberserver#302]
it spams log with messages like this:
```
2019-02-06 22:37:39 ERROR twistedserver.dataReceived:56  Error in handling data from client:  123.123.123.123 53584 (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT ban.id AS ban_id, ban.issuer_user_id AS ban_issuer_user_id, ban.user_id AS ban_user_id, ban.ip AS ban_ip, ban.email AS ban_email, ban.reason AS ban_reason, ban.end_date AS ban_end_date \nFROM ban \nWHERE ban.user_id = %s AND ban.end_date >= %s \n LIMIT %s'] [parameters: [immutabledict({})]], b'#2 LOGIN .....\n', Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1069, in _execute_context
    conn = self.__connection
AttributeError: 'Connection' object has no attribute '_Connection__connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 158, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 194, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 164, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 346, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 979, in in_LOGIN
    good, user_or_error = self.userdb.login_user(username, password, client.ip_address, lobby_id, user_id, local_ip, client.country_code)
  File "/home/lobby/uberserver/SQLUsers.py", line 392, in login_user
    dbban = self._root.bandb.check_ban(dbuser.id, ip, dbuser.email, now)
  File "/home/lobby/uberserver/SQLUsers.py", line 681, in check_ban
    userban = self.sess().query(Ban).filter(Ban.user_id == user_id, now <= Ban.end_date).first()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT ban.id AS ban_id, ban.issuer_user_id AS ban_issuer_user_id, ban.user_id AS ban_user_id, ban.ip AS ban_ip, ban.email AS ban_email, ban.reason AS ban_reason, ban.end_date AS ban_end_date \nFROM ban \nWHERE ban.user_id = %s AND ban.end_date >= %s \n LIMIT %s'] [parameters: [immutabledict({})]]

```

IMHO this error should be catched / connection to db restored at least when a user logs in.

**Comment by silentwings** [comment]
2019-02-14 18:27:21 INFO  DataHandler.clean:217  scheduled clean...
2019-02-14 18:27:21 INFO  SQLUsers.clean:653  deleting 0 users who failed to verify registration
2019-02-14 18:27:21 INFO  SQLUsers.clean:658  deleting 16 inactive users with no ingame time
2019-02-14 18:27:22 INFO  SQLUsers.clean:663  deleting 0 very inactive users
2019-02-14 18:27:23 INFO  SQLUsers.clean:668  deleting 0 channel history messages
2019-02-14 18:27:23 ERROR DataHandler.clean:225  Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lobbydev/uberserver/DataHandler.py", line 220, in clean
    self.bridgeduserdb.clean()
  File "/home/lobbydev/uberserver/SQLUsers.py", line 839, in clean
    logging.info("deleting %i inactive bridged users", response.count())
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2980, in count
    return self.from_self(col).scalar()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2749, in scalar
    ret = self.one()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2718, in one
    ret = list(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT bridged_users.id AS bridged_users_id, bridged_users.external_id AS bridged_users_external_id, bridged_users.location AS bridged_users_location, bridged_users.external_username AS bridged_users_external_username, bridged_users.last_bridged AS bridged_users_last_bridged \nFROM bridged_users \nWHERE bridged_users.last_bridged < %s) AS anon_1'] [parameters: (datetime.datetime(2018, 2, 14, 18, 27, 23, 176873),)]

2019-02-14 18:27:23 INFO  DataHandler.clean:226  scheduled clean finished
2019-02-14 20:15:57 INFO  Protocol._new:292  [15] Client connected from 185.129.148.159:1472
2019-02-14 20:15:57 INFO  Protocol._remove:298  [15] disconnected from 185.129.148.159: Connection was aborted locally, using.
2019-02-14 21:31:53 INFO  Protocol._new:292  [16] Client connected from 86.142.220.36:60459
2019-02-14 21:31:54 ERROR twistedserver.dataReceived:56  Error in handling data from client:  86.142.220.36 60459 (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: 'SELECT ban.id AS ban_id, ban.issuer_user_id AS ban_issuer_user_id, ban.user_id AS ban_user_id, ban.ip AS ban_ip, ban.email AS ban_email, ban.reason AS ban_reason, ban.end_date AS ban_end_date \nFROM ban \nWHERE ban.user_id = %s AND ban.end_date >= %s \n LIMIT %s'] [parameters: (67292, datetime.datetime(2019, 2, 14, 21, 31, 54, 26867), 1)], b'#2 LOGIN [Fx]Bluestone oA3Vz/4FWrEIISXKq4slcw== 0 192.168.1.244 SpringLobby 0.267-22-g12edf2c (unix x64)\t3352949570\tsp cl u l\n', Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lobbydev/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobbydev/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobbydev/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobbydev/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 412, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1017, in in_LOGIN
    banned, reason = self.userdb.check_banned(username, client.ip_address)
  File "/home/lobbydev/uberserver/SQLUsers.py", line 477, in check_banned
    dbban = self._root.bandb.check_ban(dbuser.id, ip, dbuser.email, now)
  File "/home/lobbydev/uberserver/SQLUsers.py", line 861, in check_ban
    userban = self.sess().query(Ban).filter(Ban.user_id == user_id, now <= Ban.end_date).first()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: 'SELECT ban.id AS ban_id, ban.issuer_user_id AS ban_issuer_user_id, ban.user_id AS ban_user_id, ban.ip AS ban_ip, ban.email AS ban_email, ban.reason AS ban_reason, ban.end_date AS ban_end_date \nFROM ban \nWHERE ban.user_id = %s AND ban.end_date >= %s \n LIMIT %s'] [parameters: (67292, datetime.datetime(2019, 2, 14, 21, 31, 54, 26867), 1)]

2019-02-14 21:32:16 INFO  Protocol.out_SERVERMSG:3186  [16] <>: JOIN failed. Insufficient rights.
2019-02-14 21:32:20 INFO  Protocol._remove:298  [16] disconnected from 86.142.220.36: Connection to the other side was lost in a non-clean fashion: Connection lost.
2019-02-14 21:32:23 INFO  Protocol._new:292  [17] Client connected from 86.142.220.36:60460
2019-02-14 21:32:24 ERROR twistedserver.dataReceived:56  Error in handling data from client:  86.142.220.36 60460 (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT ban.id AS ban_id, ban.issuer_user_id AS ban_issuer_user_id, ban.user_id AS ban_user_id, ban.ip AS ban_ip, ban.email AS ban_email, ban.reason AS ban_reason, ban.end_date AS ban_end_date \nFROM ban \nWHERE ban.user_id = %s AND ban.end_date >= %s \n LIMIT %s'] [parameters: [immutabledict({})]], b'#2 LOGIN [Fx]Bluestone oA3Vz/4FWrEIISXKq4slcw== 0 192.168.1.244 SpringLobby 0.267-22-g12edf2c (unix x64)\t3352949570\tsp cl u l\n', Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1069, in _execute_context
    conn = self.__connection
AttributeError: 'Connection' object has no attribute '_Connection__connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lobbydev/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobbydev/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobbydev/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobbydev/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 412, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1017, in in_LOGIN
    banned, reason = self.userdb.check_banned(username, client.ip_address)
  File "/home/lobbydev/uberserver/SQLUsers.py", line 477, in check_banned
    dbban = self._root.bandb.check_ban(dbuser.id, ip, dbuser.email, now)
  File "/home/lobbydev/uberserver/SQLUsers.py", line 861, in check_ban
    userban = self.sess().query(Ban).filter(Ban.user_id == user_id, now <= Ban.end_date).first()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT ban.id AS ban_id, ban.issuer_user_id AS ban_issuer_user_id, ban.user_id AS ban_user_id, ban.ip AS ban_ip, ban.email AS ban_email, ban.reason AS ban_reason, ban.end_date AS ban_end_date \nFROM ban \nWHERE ban.user_id = %s AND ban.end_date >= %s \n LIMIT %s'] [parameters: [immutabledict({})]]

2019-02-14 21:32:29 INFO  Protocol._remove:298  [17] disconnected from 86.142.220.36: Connection to the other side was lost in a non-clean fashion: Connection lost.

**Comment by silentwings** [comment]
This happens regularly on the dev lobby server and rarely on the live one -> likely cause is that the db connection times out if it stays idle for a long time.

**Comment by silentwings** [comment]
https://github.com/spring/uberserver/commit/46366c72d20c2d826c3fe2fd6769fc41880c449e

**Comment by silentwings** [comment]
hopefully fixed
