### ISSUE TITLE
52118 , b'#5 JOIN test \n', Traceback (most recent call last):

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#307]
File "/home/lobbydev/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobbydev/uberserver/Client.py", line 162, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobbydev/uberserver/Client.py", line 198, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobbydev/uberserver/Client.py", line 168, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 408, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1680, in in_JOIN
    channel.addUser(client)
  File "protocol/Channel.py", line 99, in addUser
    assert(bridgedClient)
AssertionError

**Comment by silentwings** [comment]
channel thinks it contains bridged client which doesn't exist globally
