### ISSUE TITLE
2019-02-18 17:40:14 ERROR twistedserver.dataReceived:56  Error in handling data from client: PicasosaciP 188.105.240.9 58818 name 'battle' is not defined, b'#31 OPENBATTLE

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#317]
2019-02-18 17:40:14 ERROR twistedserver.dataReceived:56  Error in handling data from client: PicasosaciP 188.105.240.9 58818 name 'battle' is not defined, b'#31 OPENBATTLE 0 1 * 8452 12 -839766398 0 1047841852 spring\t104.0\tCervino v1\tOn Bridge Number Nine\tMOSAIC $VERSION\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 413, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1867, in in_OPENBATTLE
    battle.joinBattle(client)
  File "protocol/Battle.py", line 68, in joinBattle
    if battle.host == client.session_id:
NameError: name 'battle' is not defined

**Comment by silentwings** [comment]
fixed and now...

2019-02-18 17:52:31 ERROR twistedserver.dataReceived:56  Error in handling data from client: rsieuz29 193.52.24.14 48582 'Chat' object has no attribute 'name', b'#11 OPENBATTLE 0 1 * 8452 2 -1267272310 0 1456003496 spring\t104.0\tSupreme Battlefield\trsieuz29\tTech Annihilation v3.06\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 413, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1867, in in_OPENBATTLE
    battle.joinBattle(client)
  File "protocol/Battle.py", line 69, in joinBattle
    raise NameError('%s is having an identity crisis' % (client.name))
AttributeError: 'Chat' object has no attribute 'name'
