### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#321]
2019-02-18 22:33:04 ERROR twistedserver.dataReceived:56  Error in handling data from client: DarkEnergy4 86.5.6.80 37590 Set changed size during iteration, b'LOGIN DarkEnergy4 I8JeAB8RchFTMPA+idA+dA== 3500 192.168.1.102 SPADS v0.12.4\t0\ta b sp cl\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 413, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1078, in in_LOGIN
    self._SendLoginInfo(client)
  File "protocol/Protocol.py", line 1103, in _SendLoginInfo
    client.RealSend(self.client_AddBattle(client, battle))
  File "protocol/Protocol.py", line 789, in client_AddBattle
    host = self.clientFromSession(battle.host)
  File "protocol/Protocol.py", line 712, in clientFromSession
    self.cleanup()
  File "protocol/Protocol.py", line 2965, in cleanup
    for session_id in battle.users:
RuntimeError: Set changed size during iteration

**Comment by silentwings** [comment]
2019-02-18 22:32:31 ERROR twistedserver.dataReceived:56  Error in handling data from client: rsieuz29 81.194.27.158 2300 112, b'#4 OPENBATTLE 0 0 * 8452 4 -1267272310 0 -1922586425 spring\t104.0\tDeltaSiegeDry\tMERDE\tTech Annihilation v3.06\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 413, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1867, in in_OPENBATTLE
    battle.joinBattle(client)
  File "protocol/Battle.py", line 75, in joinBattle
    battle_client = self._root.protocol.clientFromSession(sessionid)
  File "protocol/Protocol.py", line 712, in clientFromSession
    self.cleanup()
  File "protocol/Protocol.py", line 2982, in cleanup
    del self._root.battles[battle_id]
KeyError: 112

**Comment by silentwings** [comment]
2019-02-18 22:23:19 INFO  Protocol._remove:301  [20] <PicasosaciP> disconnected from 188.105.240.9: Connection to the other side was lost in a non-clean fashion: Connection lost.
2019-02-18 22:23:19 WARNING Protocol.out_FAILED:3210  [20] <PicasosaciP>: LEAVE __battle__1007111 is a battle, use LEAVEBATTLE to leave it
2019-02-18 22:23:27 INFO  Protocol._new:293  [435] Client connected from 188.105.240.9:60516
2019-02-18 22:23:27 INFO  Protocol._SendLoginInfo:1088  [435] <pica_bathroom> logged in (access=user).
2019-02-18 22:23:27 ERROR Protocol.clientFromSession:711  Couldn't get client from session_id: 20 NoneType: None

2019-02-18 22:23:27 ERROR Protocol.cleanup:2967  deleting session 20 in battle 53, doesn't exist
2019-02-18 22:23:27 ERROR twistedserver.dataReceived:56  Error in handling data from client: pica_bathroom 188.105.240.9 60516 Set changed size during iteration, b'#2 LOGIN pica_bathroom kS7IA7LOSeSlQQaNSVq1cA== 0 192.168.178.33 SpringLobby 0.267 (win x32)\t4284282567\ta m sp cl p\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 413, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1078, in in_LOGIN
    self._SendLoginInfo(client)
  File "protocol/Protocol.py", line 1103, in _SendLoginInfo
    client.RealSend(self.client_AddBattle(client, battle))
  File "protocol/Protocol.py", line 789, in client_AddBattle
    host = self.clientFromSession(battle.host)
  File "protocol/Protocol.py", line 712, in clientFromSession
    self.cleanup()
  File "protocol/Protocol.py", line 2965, in cleanup
    for session_id in battle.users:
RuntimeError: Set changed size during iteration
