### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'logged_in'

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#322]
2019-02-18 22:32:29 ERROR twistedserver.dataReceived:56  Error in handling data from client: Spads 2.10.253.37 55368 , b'LOGIN Spads **** 3200 192.168.1.3 SPADS v0.12.6\t0\ta b u sp cl\n', Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 413, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1078, in in_LOGIN
    self._SendLoginInfo(client)
  File "protocol/Protocol.py", line 1103, in _SendLoginInfo
    client.RealSend(self.client_AddBattle(client, battle))
  File "protocol/Protocol.py", line 789, in client_AddBattle
    host = self.clientFromSession(battle.host)
  File "protocol/Protocol.py", line 708, in clientFromSession
    assert(isinstance(session_id, int))
AssertionError

2019-02-18 22:32:31 ERROR DataHandler.broadcast:543  Traceback (most recent call last):
  File "/home/lobby/uberserver/DataHandler.py", line 541, in broadcast
    self.multicast(channel.users, msg, ignore, sourceClient, flag, not_flag)
  File "/home/lobby/uberserver/DataHandler.py", line 513, in multicast
    if not client.logged_in:
AttributeError: 'NoneType' object has no attribute 'logged_in'

**Comment by silentwings** [comment]
presumed case of #295
