### ISSUE TITLE
chanserv inconsistency with presence in registered battles, rel cleanup

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#324]
2019-02-19 18:11:00 ERROR ChanServ.Handle:70  Traceback (most recent call last):
  File "/home/lobby/uberserver/ChanServ.py", line 62, in Handle
    self.HandleMessage(None, user, msg)
  File "/home/lobby/uberserver/ChanServ.py", line 110, in HandleMessage
    response = self.HandleCommand(user, cmd, chan, args)
  File "/home/lobby/uberserver/ChanServ.py", line 151, in HandleCommand
    self.Respond('JOIN %s' % chan)
  File "/home/lobby/uberserver/ChanServ.py", line 76, in Respond
    self._root.protocol._handle(self, msg)
  File "protocol/Protocol.py", line 414, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1735, in in_JOIN
    assert(chan not in client.channels)
AssertionError

**Comment by silentwings** [comment]
2019-02-19 18:10:07 INFO  Protocol.cleanup:2962  Cleanup initiated
2019-02-19 18:10:07 ERROR Protocol.cleanup:3006  deleting channel __battle__67292, empty
2019-02-19 18:10:29 INFO  Protocol.cleanup:2962  Cleanup initiated
2019-02-19 18:10:49 INFO  Protocol.cleanup:2962  Cleanup initiated
