### ISSUE TITLE
non-reproducible SQL error with bridged clients

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#325]
edit - removed first stacktrace - this one was just #302 in disguise

**Comment by silentwings** [comment]
2019-02-21 20:52:11 ERROR twistedserver.dataReceived:56  Error in handling data from client: appservice 37.15.216.217 41130 (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT bridged_users.id AS bridged_users_id, bridged_users.external_id AS bridged_users_external_id, bridged_users.location AS bridged_users_location, bridged_users.external_username AS bridged_users_external_username, bridged_users.last_bridged AS bridged_users_last_bridged \nFROM bridged_users \nWHERE bridged_users.external_id = %s AND bridged_users.location = %s \n LIMIT %s'] [parameters: [immutabledict({})]], b'BRIDGECLIENTFROM discord 231682974729502721 TurBoss\r\n', Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1069, in _execute_context
    conn = self.__connection
AttributeError: 'Connection' object has no attribute '_Connection__connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 410, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1368, in in_BRIDGECLIENTFROM
    good, response = self._root.bridgeduserdb.bridge_user(location, external_id, external_username)
  File "/home/lobby/uberserver/SQLUsers.py", line 823, in bridge_user
    bridgedUser = self.sess().query(BridgedUser).filter(BridgedUser.external_id == external_id).filter(BridgedUser.location == location).first()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT bridged_users.id AS bridged_users_id, bridged_users.external_id AS bridged_users_external_id, bridged_users.location AS bridged_users_location, bridged_users.external_username AS bridged_users_external_username, bridged_users.last_bridged AS bridged_users_last_bridged \nFROM bridged_users \nWHERE bridged_users.external_id = %s AND bridged_users.location = %s \n LIMIT %s'] [parameters: [immutabledict({})]]

**Comment by silentwings** [comment]
I think this is #302 in disguise

**Comment by silentwings** [comment]
again

2019-02-25 02:38:22 ERROR twistedserver.dataReceived:56  Error in handling data from client: appservice 37.15.216.217 50752 (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT bridged_users.id AS bridged_users_id, bridged_users.external_id AS bridged_users_external_id, bridged_users.location AS bridged_users_location, bridged_users.external_username AS bridged_users_external_username, bridged_users.last_bridged AS bridged_users_last_bridged \nFROM bridged_users \nWHERE bridged_users.external_id = %s AND bridged_users.location = %s \n LIMIT %s'] [parameters: [immutabledict({})]], b'BRIDGECLIENTFROM freenode.org specing specing\r\n', Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1069, in _execute_context
    conn = self.__connection
AttributeError: 'Connection' object has no attribute '_Connection__connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 410, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1368, in in_BRIDGECLIENTFROM
    good, response = self._root.bridgeduserdb.bridge_user(location, external_id, external_username)
  File "/home/lobby/uberserver/SQLUsers.py", line 823, in bridge_user
    bridgedUser = self.sess().query(BridgedUser).filter(BridgedUser.external_id == external_id).filter(BridgedUser.location == location).first()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT bridged_users.id AS bridged_users_id, bridged_users.external_id AS bridged_users_external_id, bridged_users.location AS bridged_users_location, bridged_users.external_username AS bridged_users_external_username, bridged_users.last_bridged AS bridged_users_last_bridged \nFROM bridged_users \nWHERE bridged_users.external_id = %s AND bridged_users.location = %s \n LIMIT %s'] [parameters: [immutabledict({})]]

**Comment by silentwings** [comment]
2019-02-25 07:23:10 INFO  DataHandler.clean:225  scheduled clean...
2019-02-25 07:23:11 INFO  SQLUsers.clean:653  deleting 1 users who failed to verify registration
2019-02-25 07:23:11 INFO  SQLUsers.clean:658  deleting 12 inactive users with no ingame time
2019-02-25 07:23:11 INFO  SQLUsers.clean:663  deleting 0 very inactive users
2019-02-25 07:23:11 INFO  SQLUsers.clean:668  deleting 0 channel history messages
2019-02-25 07:23:12 ERROR DataHandler.clean:233  Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1069, in _execute_context
    conn = self.__connection
AttributeError: 'Connection' object has no attribute '_Connection__connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lobby/uberserver/DataHandler.py", line 228, in clean
    self.bridgeduserdb.clean()
  File "/home/lobby/uberserver/SQLUsers.py", line 839, in clean
    logging.info("deleting %i inactive bridged users", response.count())
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2980, in count
    return self.from_self(col).scalar()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2749, in scalar
    ret = self.one()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2718, in one
    ret = list(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT bridged_users.id AS bridged_users_id, bridged_users.external_id AS bridged_users_external_id, bridged_users.location AS bridged_users_location, bridged_users.external_username AS bridged_users_external_username, bridged_users.last_bridged AS bridged_users_last_bridged \nFROM bridged_users \nWHERE bridged_users.last_bridged < %s) AS anon_1'] [parameters: [immutabledict({})]]

**Comment by silentwings** [comment]
perhaps useful: https://mofanim.wordpress.com/2013/01/02/sqlalchemy-mysql-has-gone-away/

perhaps this is another version of https://github.com/spring/uberserver/issues/302

**Comment by silentwings** [comment]
Looks like we are using Session in a non-standard way:

https://docs.sqlalchemy.org/en/latest/orm/session_basics.html#when-do-i-construct-a-session-when-do-i-commit-it-and-when-do-i-close-it
is_active on https://docs.sqlalchemy.org/en/latest/orm/session_api.html

our use of is_active fails to notice if the db connection times out
probably we should be using something like
`
from contextlib import contextmanager

@contextmanager
def session_scope():
    """Provide a transactional scope around a series of operations."""
    session = Session()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()


def run_my_program():
    with session_scope() as session:
        ThingOne().go(session)
        ThingTwo().go(session)`

**Comment by silentwings** [comment]
hopefully fixed
