### ISSUE TITLE
missing backwards compat for some old bots

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#331]
2019-03-07 18:55:03 WARNING Protocol.in_LOGIN:1017  Invalid login sentence 'Spring Bot v0.2' from <StatServ>
2019-03-07 18:55:03 ERROR twistedserver.dataReceived:58  Error in handling data from client:  2.10.253.37:38328
exception: out_DENIED() missing 1 required positional argument: 'reason'
command:  b'LOGIN StatServ **** 2412 192.168.1.2 Spring Bot v0.2\n'
Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 410, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1018, in in_LOGIN
    self.out_DENIED(client, 'Invalid sentence format, please update your lobby client.')
TypeError: out_DENIED() missing 1 required positional argument: 'reason'

**Comment by silentwings** [comment]
2019-03-07 19:00:15 ERROR twistedserver.dataReceived:58  Error in handling data from client:  89.245.122.193:49180
exception: out_DENIED() missing 1 required positional argument: 'reason'
command:  b'LOGIN MelBot **** 0 * MelTraX LuaBot\n'
Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 410, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1018, in in_LOGIN
    self.out_DENIED(client, 'Invalid sentence format, please update your lobby client.')
TypeError: out_DENIED() missing 1 required positional argument: 'reason'
