### ISSUE TITLE
dangling bridged user 

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#334]
somehow, when appservice logs out Turboss:matrix.org isn't removed with it (but all other bridged users are...)

collateral damage:

exception: 'NoneType' object has no attribute 'username'
command:  b'#27 JOIN sy \n'
Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    if data.startswith('#') and len(words)>= 3:
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 410, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1716, in in_JOIN
    channel.addUser(client)
  File "protocol/Channel.py", line 89, in addUser
    if not bridge.username in bridgedClients:
AttributeError: 'NoneType' object has no attribute 'username'

**Comment by silentwings** [comment]
[06:30:01] <TurBoss> FAILED cmd=LEAVEFROM	msg=Bridged user (matrix.org,TurBoss) not found
[06:30:19] <TurBoss> FAILED cmd=UNBRIDGECLIENTFROM	msg=Bridged client (matrix.org,TurBoss) not found

**Comment by silentwings** [comment]
[08:08:53] ** Server ** <TurBoss:matrix.org> is bridged,  bridged_id=2,  bridge_user_id='None'
[08:08:53] ** Server ** Last bridged: Mar 16, 2019
[08:08:53] ** Server ** external_id=TurBoss,  location=matrix.org,

**Comment by silentwings** [comment]
2019-03-16 11:38:17 INFO  Protocol.cleanup:2901  Cleanup initiated by <[Fx]Bluestone>
2019-03-16 11:38:17 ERROR Protocol.cleanup:3041  bridged_id with missing bridge: 2<TurBoss:matrix.org> 1003742
2019-03-16 11:38:17 ERROR Protocol.cleanup:3051  deleted invalid bridged_id: 2
2019-03-16 11:38:17 ERROR Protocol.cleanup:3104  deleted invalid bridged_id 2 from channel chobby
2019-03-16 11:38:17 ERROR Protocol.cleanup:3104  deleted invalid bridged_id 2 from channel test
2019-03-16 11:38:17 ERROR Protocol.cleanup:3104  deleted invalid bridged_id 2 from channel springlobby
2019-03-16 11:38:17 ERROR Protocol.cleanup:3104  deleted invalid bridged_id 2 from channel s44
2019-03-16 11:38:17 ERROR Protocol.cleanup:3104  deleted invalid bridged_id 2 from channel mapping
2019-03-16 11:38:17 ERROR Protocol.cleanup:3104  deleted invalid bridged_id 2 from channel moddev
2019-03-16 11:38:17 ERROR Protocol.cleanup:3104  deleted invalid bridged_id 2 from channel sy
2019-03-16 11:38:17 INFO  Protocol.cleanup:3131  deleted:
 0 clients, 0 usernames, 0 user_ids
 0 bridged_locations, 0 bridged_usernames, 1 bridged_user_ids, 0 bridge_external_ids, 0 bridge_locations
 0 battles, 0 battle_users, 0 battle_pending_users
 0 channels, 0 chan

**Comment by silentwings** [comment]
hopefully fixed, root cause was perhaps already fixed
