### ISSUE TITLE
  File "protocol/Protocol.py", line 2529, in in_GETUSERINFO

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#336]
Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 52, in dataReceived
    if data.startswith('#') and len(words)>= 3:
  File "/home/lobby/uberserver/Client.py", line 161, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 197, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 167, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 406, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 2529, in in_GETUSERINFO
    self.out_SERVERMSG(client, "Registered %s,  last login %s" % (user.register_date.strftime('%b %d, %Y'), user.last_login.strftime('%b %d, %Y')))
AttributeError: 'NoneType' object has no attribute 'strftime'

**Comment by silentwings** [comment]
seems some db records have None entries
