### ISSUE TITLE
tracebacks after SETMINSPRINGVERSION 104.0

### ISSUE THREAD

**Issue by abma** [spring/uberserver#341]
i.e.:

2019-04-08 00:46:26 ERROR twistedserver.dataReceived:71  Error in handling data from client: J5 78.226.240.154:50500 
exception: 503
command:  b'#910 JOINBATTLE 501  218829ce\n'
Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 64, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 165, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 201, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 171, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 396, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1868, in in_JOINBATTLE
    self.addPendingBattle(client, battle)
  File "protocol/Protocol.py", line 1876, in addPendingBattle
    self.removePendingBattle(client)
  File "protocol/Protocol.py", line 1882, in removePendingBattle
    pending_battle = self._root.battles[client.pending_battle]
KeyError: 503

**Comment by silentwings** [comment]
Are these re-occuring reguarly, or just happened when the command was called?

**Comment by abma** [comment]
it looked like re-occuring: very likely they'll stop when the affected client(s) reconnected: but i didn't really investigate.

regardingless of that, IMHO removePendingBattle should check if the battle exists:
https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L1880

for safety reasons all remove/close/disconnect... functions should have safety checks?!

**Comment by silentwings** [comment]
A pending user should only ever be marked as pending for a battle that exists, and a battle should remove/clean-up any pending users when it is closed.

Adding a "safety" check for this (of the form 'if battle exists do xyz') would increase the chance that some inconsistency is allowed to preserve undetected.

**Comment by abma** [comment]
at a quick look, it seems Protocol.removeBattle() isn't called at all in in_SETMINSPRINGVERSION()

only broadcast_RemoveBattle() which doesn't set client.pending_battle=None

**Comment by silentwings** [comment]
yep that would do it

**Comment by abma** [comment]
> Adding a "safety" check (of the form 'if the battle exists, only then remove the pending user') would increase the chance that some inconsistency is allowed to preserve undetected.

agreed :-|
