### ISSUE TITLE
traceback on RESETPASSWORDREQUEST

### ISSUE THREAD

**Issue by abma** [spring/uberserver#358]
exception: unorderable types: NoneType() < NoneType()
command:  b'RESETPASSWORDREQUEST <some mail address>\r\n'
Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 64, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 165, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 201, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 171, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 398, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 3077, in in_RESETPASSWORDREQUEST
    good, response = self.userdb.get_user_id_with_email(email)
  File "/home/lobby/uberserver/SQLUsers.py", line 638, in get_user_id_with_email
    if entry.register_date < dbuser.register_date:
TypeError: unorderable types: NoneType() < NoneType()

**Comment by abma** [comment]
shall we set a register date for users where no date is known?

**Comment by silentwings** [comment]
oh, forgot those existed ... will deal with it shortly, not sure whats the best way atm
