### ISSUE TITLE
exception: 'NoneType' object has no attribute 'username'

### ISSUE THREAD

**Issue by abma** [spring/uberserver#388]
2021-12-05 14:51:49 ERROR twistedserver.dataReceived:71  Error in handling data from client: [AG]abma
exception: 'NoneType' object has no attribute 'username'
command:  b'#5 JOIN sy \n'
Traceback (most recent call last):
  File "/home/lobby/uberserver/twistedserver.py", line 64, in dataReceived
    self.Handle(data.decode("utf-8"))
  File "/home/lobby/uberserver/Client.py", line 166, in Handle
    self.HandleProtocolCommands(self.data.split("\n"), flood_limits)
  File "/home/lobby/uberserver/Client.py", line 202, in HandleProtocolCommands
    self.HandleProtocolCommand(command)
  File "/home/lobby/uberserver/Client.py", line 172, in HandleProtocolCommand
    self._root.protocol._handle(self, cmd)
  File "protocol/Protocol.py", line 397, in _handle
    function(*([client] + fun_args))
  File "protocol/Protocol.py", line 1667, in in_JOIN
    channel.addUser(client)
  File "protocol/Channel.py", line 91, in addUser
    if not bridge.username in bridgedClients:
AttributeError: 'NoneType' object has no attribute 'username'

**Comment by abma** [comment]
->

2021-12-05 15:51:24 INFO  Protocol.cleanup:2787  Cleanup initiated by <[AG]abma>
2021-12-05 15:51:24 ERROR Protocol.cleanup:2832  client with missing username:  368814
2021-12-05 15:51:24 ERROR Protocol.cleanup:2841  deleted invalid client:  368814
2021-12-05 15:51:24 ERROR Protocol.cleanup:2939  bridged_id with missing bridge: 1604<TurBoss:matrix.org> 1019781
2021-12-05 15:51:24 ERROR Protocol.cleanup:2939  bridged_id with missing bridge: 1592<TurBoss:jauriarts.org> 1019781
2021-12-05 15:51:24 ERROR Protocol.cleanup:2939  bridged_id with missing bridge: 1578<abma:springrts.com> 1019781
2021-12-05 15:51:24 ERROR Protocol.cleanup:2954  deleted invalid bridged_id: 1604
2021-12-05 15:51:24 ERROR Protocol.cleanup:2954  deleted invalid bridged_id: 1592
2021-12-05 15:51:24 ERROR Protocol.cleanup:2954  deleted invalid bridged_id: 1578
2021-12-05 15:51:24 ERROR Protocol.cleanup:3009  deleted invalid bridged_id 1578 from channel springlobby
2021-12-05 15:51:24 ERROR Protocol.cleanup:3009  deleted invalid bridged_id 1578 from channel sy
2021-12-05 15:51:24 ERROR Protocol.cleanup:3009  deleted invalid bridged_id 1578 from channel test
2021-12-05 15:51:24 ERROR Protocol.cleanup:3016  deleted empty channel springLobby
2021-12-05 15:51:24 ERROR Protocol.cleanup:3016  deleted empty channel King
2021-12-05 15:51:24 ERROR Protocol.cleanup:3016  deleted empty channel SWIW
2021-12-05 15:51:24 ERROR Protocol.cleanup:3016  deleted empty channel SY
2021-12-05 15:51:24 INFO  Protocol.cleanup:3030  deleted:
 1 clients, 0 usernames, 0 user_ids
 0 bridged_locations, 0 bridged_usernames, 3 bridged_user_ids, 0 bridge_external_ids, 0 bridge_locations
 0 battles, 0 battle_users, 0 battle_pending_users
 4 channels, 0 channel_users, 3 channel_bridged_users
 found 0 mismatches

**Comment by abma** [comment]
after the cleanup the stracktrace when joining #sy is gone it seem.s
