### ISSUE TITLE
pip install -r requirements.txt error

### ISSUE THREAD

**Issue by scorbin** [spring/uberserver#389]
Python 3.8.10
I tried running the pip install got the follow error.  Thanks 

Collecting GeoIP==1.3.2
  Using cached GeoIP-1.3.2.tar.gz (20 kB)
Collecting mysqlclient==1.3.10
  Using cached mysqlclient-1.3.10.tar.gz (82 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/scorbin/virtenvs/uberserver/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qwx8gcr7/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qwx8gcr7/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-qwx8gcr7/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-qwx8gcr7/mysqlclient/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qwx8gcr7/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-qwx8gcr7/mysqlclient/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-qwx8gcr7/mysqlclient/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by abma** [comment]
-> https://pypi.org/project/mysqlclient/

on debian/ubuntu:

$ sudo apt-get install python3-dev default-libmysqlclient-dev build-essential
