### ISSUE TITLE
Traceback after recent changes:

### ISSUE THREAD

**Issue by abma** [spring/uberserver#84]
2014-05-05T04:30:45 ------------------------------------------------------------
2014-05-05T04:30:45 Traceback (most recent call last):
2014-05-05T04:30:45   File "/home/lobby/uberserver/Dispatcher.py", line 49, in callback
2014-05-05T04:30:45     self.socketmap[s].FlushBuffer()
2014-05-05T04:30:45   File "/home/lobby/uberserver/Client.py", line 190, in FlushBuffer
2014-05-05T04:30:45     self.handler.poller.setoutput(self.conn, bool(self.sendbuffer or self.sendingmessage))
2014-05-05T04:30:45   File "/home/lobby/uberserver/Multiplexer.py", line 45, in setoutput
2014-05-05T04:30:45     self.poller.modify(s, eventmask) # not valid for select.poll before python 2.6, might need to replace with register() in this context
2014-05-05T04:30:45 IOError: [Errno 2] No such file or directory

i don't understand this error yet...

invalid fd?!

seems to happen always on disconnect, maybe just some logic error: connection is already closed, but data should be send / re-registered to poll

**Comment by abma** [comment]
this code doesn't exist any more...
